package com.dsmjd.android.dev.mlcdemo.models;

import java.util.Date;

public class User {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column user.id
     *
     * @ibatorgenerated Mon Nov 23 16:50:44 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column user.account
     *
     * @ibatorgenerated Mon Nov 23 16:50:44 CST 2015
     */
    private String account;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column user.nickName
     *
     * @ibatorgenerated Mon Nov 23 16:50:44 CST 2015
     */
    private String nickname;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column user.password
     *
     * @ibatorgenerated Mon Nov 23 16:50:44 CST 2015
     */
    private String password;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column user.mobile
     *
     * @ibatorgenerated Mon Nov 23 16:50:44 CST 2015
     */
    private String mobile;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column user.cardtype
     *
     * @ibatorgenerated Mon Nov 23 16:50:44 CST 2015
     */
    private String cardtype;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column user.cardnum
     *
     * @ibatorgenerated Mon Nov 23 16:50:44 CST 2015
     */
    private String cardnum;

    private String useraddress;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column user.iconurl
     *
     * @ibatorgenerated Mon Nov 23 16:50:44 CST 2015
     */
    private String iconurl;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column user.email
     *
     * @ibatorgenerated Mon Nov 23 16:50:44 CST 2015
     */
    private String email;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column user.name
     *
     * @ibatorgenerated Mon Nov 23 16:50:44 CST 2015
     */
    private String name;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column user.birthday
     *
     * @ibatorgenerated Mon Nov 23 16:50:44 CST 2015
     */
    private Date birthday;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column user.type
     *
     * @ibatorgenerated Mon Nov 23 16:50:44 CST 2015
     */
    private Integer type;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column user.state
     *
     * @ibatorgenerated Mon Nov 23 16:50:44 CST 2015
     */
    private Integer state;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column user.time
     *
     * @ibatorgenerated Mon Nov 23 16:50:44 CST 2015
     */
//    private Date time;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column user.item1
     *
     * @ibatorgenerated Mon Nov 23 16:50:44 CST 2015
     */
    private String item1;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column user.item2
     *
     * @ibatorgenerated Mon Nov 23 16:50:44 CST 2015
     */
    private String item2;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column user.item3
     *
     * @ibatorgenerated Mon Nov 23 16:50:44 CST 2015
     */
    private String item3;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column user.item4
     *
     * @ibatorgenerated Mon Nov 23 16:50:44 CST 2015
     */
    private String item4;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column user.item5
     *
     * @ibatorgenerated Mon Nov 23 16:50:44 CST 2015
     */
    private String item5;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column user.item6
     *
     * @ibatorgenerated Mon Nov 23 16:50:44 CST 2015
     */
    private String item6;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column user.id
     *
     * @return the value of user.id
     * @ibatorgenerated Mon Nov 23 16:50:44 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column user.id
     *
     * @param id the value for user.id
     * @ibatorgenerated Mon Nov 23 16:50:44 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column user.account
     *
     * @return the value of user.account
     * @ibatorgenerated Mon Nov 23 16:50:44 CST 2015
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column user.account
     *
     * @param account the value for user.account
     * @ibatorgenerated Mon Nov 23 16:50:44 CST 2015
     */
    public void setAccount(String account) {
        this.account = account;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column user.nickName
     *
     * @return the value of user.nickName
     * @ibatorgenerated Mon Nov 23 16:50:44 CST 2015
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column user.nickName
     *
     * @param nickname the value for user.nickName
     * @ibatorgenerated Mon Nov 23 16:50:44 CST 2015
     */
    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column user.password
     *
     * @return the value of user.password
     * @ibatorgenerated Mon Nov 23 16:50:44 CST 2015
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column user.password
     *
     * @param password the value for user.password
     * @ibatorgenerated Mon Nov 23 16:50:44 CST 2015
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column user.mobile
     *
     * @return the value of user.mobile
     * @ibatorgenerated Mon Nov 23 16:50:44 CST 2015
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column user.mobile
     *
     * @param mobile the value for user.mobile
     * @ibatorgenerated Mon Nov 23 16:50:44 CST 2015
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column user.cardtype
     *
     * @return the value of user.cardtype
     * @ibatorgenerated Mon Nov 23 16:50:44 CST 2015
     */
    public String getCardtype() {
        return cardtype;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column user.cardtype
     *
     * @param cardtype the value for user.cardtype
     * @ibatorgenerated Mon Nov 23 16:50:44 CST 2015
     */
    public void setCardtype(String cardtype) {
        this.cardtype = cardtype;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column user.cardnum
     *
     * @return the value of user.cardnum
     * @ibatorgenerated Mon Nov 23 16:50:44 CST 2015
     */
    public String getCardnum() {
        return cardnum;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column user.cardnum
     *
     * @param cardnum the value for user.cardnum
     * @ibatorgenerated Mon Nov 23 16:50:44 CST 2015
     */
    public void setCardnum(String cardnum) {
        this.cardnum = cardnum;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column user.iconurl
     *
     * @return the value of user.iconurl
     * @ibatorgenerated Mon Nov 23 16:50:44 CST 2015
     */
    public String getIconurl() {
        return iconurl;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column user.iconurl
     *
     * @param iconurl the value for user.iconurl
     * @ibatorgenerated Mon Nov 23 16:50:44 CST 2015
     */
    public void setIconurl(String iconurl) {
        this.iconurl = iconurl;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column user.email
     *
     * @return the value of user.email
     * @ibatorgenerated Mon Nov 23 16:50:44 CST 2015
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column user.email
     *
     * @param email the value for user.email
     * @ibatorgenerated Mon Nov 23 16:50:44 CST 2015
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column user.name
     *
     * @return the value of user.name
     * @ibatorgenerated Mon Nov 23 16:50:44 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column user.name
     *
     * @param name the value for user.name
     * @ibatorgenerated Mon Nov 23 16:50:44 CST 2015
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column user.birthday
     *
     * @return the value of user.birthday
     * @ibatorgenerated Mon Nov 23 16:50:44 CST 2015
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column user.birthday
     *
     * @param birthday the value for user.birthday
     * @ibatorgenerated Mon Nov 23 16:50:44 CST 2015
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column user.type
     *
     * @return the value of user.type
     * @ibatorgenerated Mon Nov 23 16:50:44 CST 2015
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column user.type
     *
     * @param type the value for user.type
     * @ibatorgenerated Mon Nov 23 16:50:44 CST 2015
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column user.state
     *
     * @return the value of user.state
     * @ibatorgenerated Mon Nov 23 16:50:44 CST 2015
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column user.state
     *
     * @param state the value for user.state
     * @ibatorgenerated Mon Nov 23 16:50:44 CST 2015
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column user.time
     *
     * @return the value of user.time
     *
     * @ibatorgenerated Mon Nov 23 16:50:44 CST 2015
     */
//    public Date getTime() {
//        return time;
//    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column user.time
     *
     * @param time the value for user.time
     *
     * @ibatorgenerated Mon Nov 23 16:50:44 CST 2015
     */
//    public void setTime(Date time) {
//        this.time = time;
//    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column user.item1
     *
     * @return the value of user.item1
     * @ibatorgenerated Mon Nov 23 16:50:44 CST 2015
     */
    public String getItem1() {
        return item1;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column user.item1
     *
     * @param item1 the value for user.item1
     * @ibatorgenerated Mon Nov 23 16:50:44 CST 2015
     */
    public void setItem1(String item1) {
        this.item1 = item1;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column user.item2
     *
     * @return the value of user.item2
     * @ibatorgenerated Mon Nov 23 16:50:44 CST 2015
     */
    public String getItem2() {
        return item2;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column user.item2
     *
     * @param item2 the value for user.item2
     * @ibatorgenerated Mon Nov 23 16:50:44 CST 2015
     */
    public void setItem2(String item2) {
        this.item2 = item2;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column user.item3
     *
     * @return the value of user.item3
     * @ibatorgenerated Mon Nov 23 16:50:44 CST 2015
     */
    public String getItem3() {
        return item3;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column user.item3
     *
     * @param item3 the value for user.item3
     * @ibatorgenerated Mon Nov 23 16:50:44 CST 2015
     */
    public void setItem3(String item3) {
        this.item3 = item3;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column user.item4
     *
     * @return the value of user.item4
     * @ibatorgenerated Mon Nov 23 16:50:44 CST 2015
     */
    public String getItem4() {
        return item4;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column user.item4
     *
     * @param item4 the value for user.item4
     * @ibatorgenerated Mon Nov 23 16:50:44 CST 2015
     */
    public void setItem4(String item4) {
        this.item4 = item4;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column user.item5
     *
     * @return the value of user.item5
     * @ibatorgenerated Mon Nov 23 16:50:44 CST 2015
     */
    public String getItem5() {
        return item5;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column user.item5
     *
     * @param item5 the value for user.item5
     * @ibatorgenerated Mon Nov 23 16:50:44 CST 2015
     */
    public void setItem5(String item5) {
        this.item5 = item5;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column user.item6
     *
     * @return the value of user.item6
     * @ibatorgenerated Mon Nov 23 16:50:44 CST 2015
     */
    public String getItem6() {
        return item6;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column user.item6
     *
     * @param item6 the value for user.item6
     * @ibatorgenerated Mon Nov 23 16:50:44 CST 2015
     */
    public void setItem6(String item6) {
        this.item6 = item6;
    }


    /**
     * @return the useraddress
     */
    public String getUseraddress() {
        return useraddress;
    }

    /**
     * @param useraddress the useraddress to set
     */
    public void setUseraddress(String useraddress) {
        this.useraddress = useraddress;
    }


    /* (non-Javadoc)
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString() {
        return "User [id=" + id + ", account=" + account + ", nickname="
                + nickname + ", password=" + password + ", mobile=" + mobile
                + ", cardtype=" + cardtype + ", cardnum=" + cardnum
                + ", useraddress=" + useraddress + ", iconurl=" + iconurl
                + ", email=" + email + ", name=" + name + ", birthday="
                + birthday + ", type=" + type + ", state=" + state + ", time="
                + ", item1=" + item1 + ", item2=" + item2 + ", item3="
                + item3 + ", item4=" + item4 + ", item5=" + item5 + ", item6="
                + item6 + "]";
    }
}